### ISSUE TITLE
Embedのみのメッセージの読み上げ

### ISSUE THREAD

**Issue by siloneco** [micelle/dc_DiSpeak#29]
今まで読まれていなかったEmbedのみのメッセージが読み上げされるようになっているようです。
(サーバーと送信者の名前のみ読まれ、Embed本体は読み上げされない)
Embedのみのメッセージは読まれない方が良いと思います👍 

Ver. 2.4.0-Alpha1

**Comment by micelle** [comment]
情報ありがとうございます。
たしかに埋め込みメッセージだけの時だと空ですね…

これは読み上げないようにしておきます！（読み上げさせた場合、文字数長かったり荒ぶったりでヤバいことになりそうですし…ｗ）

**Comment by siloneco** [comment]
ありがとうございます！
ついでにピン止めなどのシステムメッセージも同様の事が起きることを確認しました
