### ISSUE TITLE
スクロールバー増殖 & ウィンドウが崩れるバグについて

### ISSUE THREAD

**Issue by siloneco** [micelle/dc_DiSpeak#43]
DiSpeak 2.4.0にて右側のスクロールバーが2つに増えたりウィンドウが崩れるバグを発見したので報告しておきます。
バグ再現動画には各サーバーの情報が含まれているためTwitterのDMに送っておきます。
今後とも開発頑張ってください！

**Comment by micelle** [comment]
## 再現
1. フルスクリーンにする
2. リロードする
3. フルスクリーンを解除する
4. `<div class="hiddendiv common"></div>`の影響でスクロールバーができてしまう
## 対策
フルスクリーン解除時に`M.textareaAutoResize($('#request_textarea'));`を行なう
## コード例
```
// Main Process
mainWindow.on('unmaximize', () => {
  mainWindow.webContents.send('unmaximize');
});

// Renderer Process
ipcRenderer.on('unmaximize', (event) => {
  M.textareaAutoResize($('#request_textarea'));
});
```
